language: node_js
node_js:
  - 12 # use node.js v12
cache: npm
branches:
  only:
    - dev # build development branch only
before_script:
  - node decrypt.js $DECRYPT_TOKEN # decrypt the encrypted files
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: master # deploy to branch 'master'
  on:
    branch: dev
  local-dir: public
after_script:
  - node cleanup.js # clean up the decrypted files