language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - dev # build development branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  cleanup: false
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: master #部署到master分支
  on:
    branch: dev
  local-dir: public
